name: LocalStack Dev Environment

on:
  workflow_dispatch:

jobs:
  localstack:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,dynamodb,lambda
          DEBUG: 1
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Wait for LocalStack
        run: |
          until curl -s http://localhost:4566/_localstack/health | grep 'running'; do sleep 2; done
      - name: Setup AWS CLI
        run: |
          pip install awscli-local[ver1]
      - name: Create DynamoDB Table
        run: |
          awslocal dynamodb create-table --table-name Movies \
            --attribute-definitions AttributeName=title,AttributeType=S AttributeName=titleHash,AttributeType=S \
            --key-schema AttributeName=title,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --global-secondary-indexes '[{"IndexName":"titleHash-index","KeySchema":[{"AttributeName":"titleHash","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"},"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1}}]'
      - name: Create S3 Buckets
        run: |
          awslocal s3 mb s3://movie-json-bucket
          awslocal s3 mb s3://asset-bucket
      - name: List resources
        run: |
          awslocal dynamodb list-tables
          awslocal s3 ls
      # Add more setup steps as needed
